# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tCwBm7I5q_Wv8MwJD7ouU6lPTzDfAAl
"""

import pandas as pd

df_loan = pd.read_csv('"C:\Users\admin\OneDrive\Desktop\studies\SOAI Internship\loan_applications.csv"')
df_txn = pd.read_csv('"C:\Users\admin\OneDrive\Desktop\studies\SOAI Internship\transactions.csv"')

print("Loan Applications:")
display(df_loan.head())
print("\nTransactions:")
display(df_txn.head())

df_loan.info()
df_txn.info()

txn_agg = df_txn.groupby('customer_id').agg({
    'transaction_amount': ['mean', 'sum', 'max', 'min'],
    'is_international_transaction': 'mean',
    'transaction_id': 'count'
}).reset_index()

txn_agg.columns = [
    'customer_id',
    'avg_txn_amt', 'total_txn_amt', 'max_txn_amt', 'min_txn_amt',
    'intl_txn_ratio',
    'txn_count'
]

merged_df = pd.merge(df_loan, txn_agg, on='customer_id', how='left')

print(merged_df.shape)
merged_df.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

plt.figure(figsize=(6,4))
sns.countplot(x='fraud_flag', data=merged_df)
plt.title('Fraud vs Non-Fraud Distribution')
plt.xlabel('Fraud Flag (0 = Genuine, 1 = Fraud)')
plt.ylabel('Count')
plt.show()

print(merged_df['fraud_flag'].value_counts(normalize=True))

num_cols = [
    'loan_amount_requested', 'loan_tenure_months', 'interest_rate_offered',
    'monthly_income', 'existing_emis_monthly', 'debt_to_income_ratio',
    'applicant_age', 'number_of_dependents',
    'avg_txn_amt', 'total_txn_amt', 'max_txn_amt', 'min_txn_amt', 'txn_count',
    'intl_txn_ratio'
]

merged_df[num_cols].hist(figsize=(18,12), bins=30, color='skyblue', edgecolor='black')
plt.suptitle('Histograms of Numeric Features', fontsize=20)
plt.tight_layout()
plt.show()

cat_cols = [
    'loan_type', 'purpose_of_loan', 'employment_status', 'property_ownership_status',
    'gender'
]

for col in cat_cols:
    plt.figure(figsize=(6,3))
    sns.countplot(x=col, data=merged_df, order=merged_df[col].value_counts().index)
    plt.title(f'Distribution of {col}')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

num_cols = [
    'loan_amount_requested', 'loan_tenure_months', 'interest_rate_offered',
    'monthly_income', 'existing_emis_monthly', 'debt_to_income_ratio',
    'applicant_age', 'number_of_dependents',
    'avg_txn_amt', 'total_txn_amt', 'max_txn_amt', 'min_txn_amt', 'txn_count',
    'intl_txn_ratio'
]

for col in num_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='fraud_flag', y=col, data=merged_df, palette='Set2')
    plt.title(f'{col} vs Fraud')
    plt.xlabel('Fraud (0=No, 1=Yes)')
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

cat_cols = [
    'loan_type', 'purpose_of_loan', 'employment_status',
    'property_ownership_status', 'gender'
]

for col in cat_cols:
    crosstab = pd.crosstab(merged_df[col], merged_df['fraud_flag'], normalize='index')
    crosstab.plot(kind='bar', stacked=True, figsize=(6,4), colormap='coolwarm')
    plt.title(f'Fraud Distribution across {col}')
    plt.ylabel('Proportion')
    plt.xlabel(col)
    plt.legend(title='Fraud Flag', labels=['Not Fraud (0)', 'Fraud (1)'])
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

drop_cols = [
    'application_id', 'customer_id', 'application_date',
    'transaction_id', 'transaction_date', 'transaction_notes',
    'ip_address', 'residential_address', 'transaction_source_destination',
    'merchant_name', 'transaction_location'
]

merged_df.drop(columns=[col for col in drop_cols if col in merged_df.columns], inplace=True)

from sklearn.preprocessing import LabelEncoder
import pandas as pd

label_enc_cols = [ 'transaction_status']
one_hot_enc_cols = ['loan_type', 'purpose_of_loan', 'merchant_category', 'device_used','gender', 'employment_status', 'property_ownership_status']

le = LabelEncoder()

for col in label_enc_cols:
    if col in merged_df.columns:
        if merged_df[col].nunique() == 2:
            merged_df[col] = le.fit_transform(merged_df[col])
        else:
            print(f" Column '{col}' has more than 2 unique values. Skipping label encoding.")

merged_df = pd.get_dummies(merged_df, columns=[col for col in one_hot_enc_cols if col in merged_df.columns], drop_first=True)

print("Encoding completed. New shape:", merged_df.shape)

merged_df['loan_to_income_ratio'] = merged_df['loan_amount_requested'] / (merged_df['monthly_income'] + 1)

merged_df['emi_to_income_ratio'] = merged_df['existing_emis_monthly'] / (merged_df['monthly_income'] + 1)

merged_df['interest_burden'] = merged_df['interest_rate_offered'] * merged_df['loan_amount_requested'] / (merged_df['monthly_income'] + 1)

merged_df['high_intl_txn'] = (merged_df['intl_txn_ratio'] > 0.4).astype(int)

merged_df['age_group'] = pd.cut(merged_df['applicant_age'], bins=[18, 30, 45, 60, 100], labels=['Young', 'Mid-Age', 'Senior', 'Elder'])

merged_df = pd.get_dummies(merged_df, columns=['age_group'], drop_first=True)

missing_values = merged_df.isnull().sum()

missing_values = missing_values[missing_values > 0]
print("🔎 Columns with missing values:\n", missing_values)

merged_df.drop(columns=['fraud_type'], inplace=True)

txn_features = ['avg_txn_amt', 'total_txn_amt', 'max_txn_amt',
                'min_txn_amt', 'intl_txn_ratio', 'txn_count']

merged_df[txn_features] = merged_df[txn_features].fillna(0)

print("Remaining Missing Values:\n", merged_df.isnull().sum())

print("Final shape of dataset:", merged_df.shape)
print("Feature columns:\n", merged_df.columns.tolist())
print("Target variable:", 'fraud_flag')

from sklearn.preprocessing import LabelEncoder
import pandas as pd

X = merged_df.drop(columns=['fraud_flag'])
y = merged_df['fraud_flag']

categorical_cols = X.select_dtypes(include='object').columns.tolist()

le = LabelEncoder()
one_hot_enc_cols = []

for col in categorical_cols:
    if X[col].nunique() == 2:
        X[col] = le.fit_transform(X[col])
    else:
        one_hot_enc_cols.append(col)

X = pd.get_dummies(X, columns=one_hot_enc_cols, drop_first=True)

print("Encoding completed.")
print("Final shape of features:", X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Data split into train and test sets.")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

print("Model training completed.")

y_pred = rf_model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

importances = rf_model.feature_importances_
features = X_train.columns
feature_df = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_df = feature_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', data=feature_df.head(15))
plt.title("Top 15 Important Features")
plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_prob = rf_model.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
auc_score = roc_auc_score(y_test, y_prob)

plt.figure(figsize=(8, 5))
plt.plot(fpr, tpr, label=f'ROC Curve (AUC = {auc_score:.2f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_prob)

plt.figure(figsize=(8, 5))
plt.plot(recall, precision, marker='.')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.grid(True)
plt.show()